//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Percolore.Core.Properties
{
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Percolore.Core.Properties.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay deve ser maior ou igual a zero..
        /// </summary>
        internal static string Calibragem_DelayMaiorZero {
            get {
                return ResourceManager.GetString("Calibragem_DelayMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay deve ser menor ou igual a {0}.
        /// </summary>
        internal static string Calibragem_DelayMenorIgual {
            get {
                return ResourceManager.GetString("Calibragem_DelayMenorIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A calibragem não contém valor..
        /// </summary>
        internal static string Calibragem_NaoContemValor {
            get {
                return ResourceManager.GetString("Calibragem_NaoContemValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de pulsos deve ser maior que zero..
        /// </summary>
        internal static string Calibragem_QuantidadePulsosMaiorZero {
            get {
                return ResourceManager.GetString("Calibragem_QuantidadePulsosMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidade deve ser maior ou igual a zero..
        /// </summary>
        internal static string Calibragem_VelocidadeMaiorZero {
            get {
                return ResourceManager.GetString("Calibragem_VelocidadeMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidade deve ser menor ou igual a {0}.
        /// </summary>
        internal static string Calibragem_VelocidadeMenorIgual {
            get {
                return ResourceManager.GetString("Calibragem_VelocidadeMenorIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Circuito de colorante {0}].
        /// </summary>
        internal static string Colorantes_Circuito {
            get {
                return ResourceManager.GetString("Colorantes_Circuito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correpondência repetida..
        /// </summary>
        internal static string Colorantes_CorrespondenciaRepetida {
            get {
                return ResourceManager.GetString("Colorantes_CorrespondenciaRepetida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A massa específica deve ser maior que zero..
        /// </summary>
        internal static string Colorantes_MassaEspecificaObrigatoria {
            get {
                return ResourceManager.GetString("Colorantes_MassaEspecificaObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do colorante é um dado obrigatório..
        /// </summary>
        internal static string Colorantes_NomeObrigatorio {
            get {
                return ResourceManager.GetString("Colorantes_NomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        internal static string Global_UnidadeMedida_Abreviacao_Mililitro {
            get {
                return ResourceManager.GetString("Global_UnidadeMedida_Abreviacao_Mililitro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout deve ser um valor entre 0 e 65535..
        /// </summary>
        internal static string Parametors_Comunicacao_TimeoutFaixa {
            get {
                return ResourceManager.GetString("Parametors_Comunicacao_TimeoutFaixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diretório de monitoramento do arquivo dat é inválido..
        /// </summary>
        internal static string Parametros_Dat_DiretorioInvalido {
            get {
                return ResourceManager.GetString("Parametros_Dat_DiretorioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O padrão de arquivo dat é uma dado obrigatório..
        /// </summary>
        internal static string Parametros_Dat_PadraoConteudoObrigatorio {
            get {
                return ResourceManager.GetString("Parametros_Dat_PadraoConteudoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho do arquivo dat é inválido..
        /// </summary>
        internal static string Parametros_Dat_RepositorioInvalido {
            get {
                return ResourceManager.GetString("Parametros_Dat_RepositorioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceleração global deve ser maior que zero..
        /// </summary>
        internal static string Parametros_Global_AceleracaoMaiorZero {
            get {
                return ResourceManager.GetString("Parametros_Global_AceleracaoMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidade global deve ser maior que zero..
        /// </summary>
        internal static string Parametros_Global_VelocidadeMaiorZero {
            get {
                return ResourceManager.GetString("Parametros_Global_VelocidadeMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A aceleração da inicialização de circuitos deve ser maior que zero..
        /// </summary>
        internal static string Parametros_Inicializacao_AceleracaoMaiorZero {
            get {
                return ResourceManager.GetString("Parametros_Inicializacao_AceleracaoMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O pulso inicial da inicialização de circuitos deve ser maior que zero..
        /// </summary>
        internal static string Parametros_Inicializacao_PulsoInicialMaiorZero {
            get {
                return ResourceManager.GetString("Parametros_Inicializacao_PulsoInicialMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O pulso limite da inicialização de circuito deve ser maior que zero..
        /// </summary>
        internal static string Parametros_Inicializacao_PulsoLimiteMaiorZero {
            get {
                return ResourceManager.GetString("Parametros_Inicializacao_PulsoLimiteMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade de circuitos por grupo deve estar entre 3 e 5..
        /// </summary>
        internal static string Parametros_Inicializacao_QtdeCircuitosGrupoFaixa {
            get {
                return ResourceManager.GetString("Parametros_Inicializacao_QtdeCircuitosGrupoFaixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step de variação da inicialização de circuito deve ser maior que zero..
        /// </summary>
        internal static string Parametros_Inicializacao_StepVariacaoMaiorZero {
            get {
                return ResourceManager.GetString("Parametros_Inicializacao_StepVariacaoMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A variação do pulso da inicialização de circuito deve ser maior que zero..
        /// </summary>
        internal static string Parametros_Inicializacao_VariacaoPulsoMaiorZero {
            get {
                return ResourceManager.GetString("Parametros_Inicializacao_VariacaoPulsoMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A velocidade da inicialização de circuito deve ser maior que zero..
        /// </summary>
        internal static string Parametros_Inicializacao_VelocidadeMaiorZero {
            get {
                return ResourceManager.GetString("Parametros_Inicializacao_VelocidadeMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O diretório de armazenamento do log de processo é inválido..
        /// </summary>
        internal static string Parametros_Log_DiretorioLogProcessoInvalido {
            get {
                return ResourceManager.GetString("Parametros_Log_DiretorioLogProcessoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O diretório de armazenamento do log de quantidade dispensada é inválido..
        /// </summary>
        internal static string Parametros_Log_DiretorioLogQuantidadeDispensadaInvalido {
            get {
                return ResourceManager.GetString("Parametros_Log_DiretorioLogQuantidadeDispensadaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A aceleração monitoramento de circuitos deve ser maior que zero..
        /// </summary>
        internal static string Parametros_Monit_AceleracaoMaiorZero {
            get {
                return ResourceManager.GetString("Parametros_Monit_AceleracaoMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O delay do monitoramento de circuitos deve ser maior que zero..
        /// </summary>
        internal static string Parametros_Monit_DelayMaiorZero {
            get {
                return ResourceManager.GetString("Parametros_Monit_DelayMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O pulso do monitoramento de circuitos deve ser maior que 0 minutos..
        /// </summary>
        internal static string Parametros_Monit_PulsoMaiorZero {
            get {
                return ResourceManager.GetString("Parametros_Monit_PulsoMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade de circuitos por grupo deve estar entre 3 e 5..
        /// </summary>
        internal static string Parametros_Monit_QtdeCircuitosGrupoFaixa {
            get {
                return ResourceManager.GetString("Parametros_Monit_QtdeCircuitosGrupoFaixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tempo para inicializar o monitoramento de circuitos deve ser maior que 10 minutos..
        /// </summary>
        internal static string Parametros_Monit_TimerDelayIniMaiorDez {
            get {
                return ResourceManager.GetString("Parametros_Monit_TimerDelayIniMaiorDez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tempo do monitoramento de circuitos deve ser maior que 10 minutos..
        /// </summary>
        internal static string Parametros_Monit_TimerDelayMaiorDez {
            get {
                return ResourceManager.GetString("Parametros_Monit_TimerDelayMaiorDez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A velocidade monitoramento de circuitos deve ser maior que zero..
        /// </summary>
        internal static string Parametros_Monit_VelocidadeMaiorZero {
            get {
                return ResourceManager.GetString("Parametros_Monit_VelocidadeMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nível máximo de colorante deve ser maior que o nível mínimo..
        /// </summary>
        internal static string Parametros_Nivel_MaximoMaiorQueMInimo {
            get {
                return ResourceManager.GetString("Parametros_Nivel_MaximoMaiorQueMInimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nível máximo de colorante deve ser maior que zero..
        /// </summary>
        internal static string Parametros_Nivel_MaximoMaiorZero {
            get {
                return ResourceManager.GetString("Parametros_Nivel_MaximoMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nível mínimo de colorante deve ser maior que zero..
        /// </summary>
        internal static string Parametros_Nivel_MinimoMaiorZero {
            get {
                return ResourceManager.GetString("Parametros_Nivel_MinimoMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A acelaração da purga deve ser maior que zero..
        /// </summary>
        internal static string Parametros_Purga_AceleracaoMaiorZero {
            get {
                return ResourceManager.GetString("Parametros_Purga_AceleracaoMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prazo de execução da purga deve ser maior que zero..
        /// </summary>
        internal static string Parametros_Purga_PrazoExecucaoMaiorZero {
            get {
                return ResourceManager.GetString("Parametros_Purga_PrazoExecucaoMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A velocidade da purga deve ser maior que zero..
        /// </summary>
        internal static string Parametros_Purga_VelocidadeMaiorZero {
            get {
                return ResourceManager.GetString("Parametros_Purga_VelocidadeMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O volume da purga deve ser maior que zero..
        /// </summary>
        internal static string Parametros_Purga_VolumeMaiorZero {
            get {
                return ResourceManager.GetString("Parametros_Purga_VolumeMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor da unidade shot deve ser maior que zero..
        /// </summary>
        internal static string Parametros_UnidadeMedida_ShotMaiorZero {
            get {
                return ResourceManager.GetString("Parametros_UnidadeMedida_ShotMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É obrigatório selecionar uma unidade de medida para entrada do usuário..
        /// </summary>
        internal static string Parametros_UnidadeMedida_UnidadeEntradaObrigatoria {
            get {
                return ResourceManager.GetString("Parametros_UnidadeMedida_UnidadeEntradaObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É obrigatório selecionar a unidade de medida que o usuário visualizará no controle de nível..
        /// </summary>
        internal static string Parametros_UnidadeMedida_UnidadeExibicaoObrigatoria {
            get {
                return ResourceManager.GetString("Parametros_UnidadeMedida_UnidadeExibicaoObrigatoria", resourceCulture);
            }
        }
    }
}
