//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Percolore.IOConnect.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Imagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Imagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Percolore.IOConnect.Properties.Imagens", typeof(Imagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAALQAAAC0CAYAAAA9zQYyAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOwgAADsIBFShKgAAAABh0RVh0U29mdHdhcmUAcGFpbnQubmV0IDQuMC45bDN+TgAAHsVJREFUeF7tnQmsbEWZx1V4j/UhIDIsCswggoCKaJCAoiIQg4qijBh1MjgoojG4rzMuow466ui4j1tUjFtwI66JinGLjk5Y1DAuGYmIwV0EF3DB+f1OVz2a+96991Sd6tPndNc/+b863fd8X321vOqqr7abVayOv/71rze/4YYbdoA7ST7vTHg04VkryfdPIcwCst+BZ/O4hV64h3EHbhdMq6hoh1BxbiupTAcQnkf4P5F8/hFhbyC+iwhi3M8k3E/bJM/bB7MrKpoW+BZUjO0IdyV8IDwFPhb+aYo38PdBAFP+MmWXPB1q8/3gJmhabhGSV7EsoOB3oOD3IjwQfgh+FA6m4qYC06+DH4GmZX++Mm21 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MensagemErro {
            get {
                return ResourceManager.GetString("MensagemErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAALQAAAC0CAYAAAA9zQYyAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOwgAADsIBFShKgAAAABh0RVh0U29mdHdhcmUAcGFpbnQubmV0IDQuMC45bDN+TgAAHsBJREFUeF7tnQnQLUV1x1V2BATZBdn3HVRcUBQEgqjAEyMGtQRBSo3BHZS4AkUoXCi2GHEhkohaIEskaKIiKJYLKRGxXLDQEiHu4hYEF8zvN7fv4/q9b5nuO/dOz9z+V/1fz3ffnJ7TZ/r27eX06QcVLIy//OUvD77//vvXgA8N3IzPTpxLPn8Z6a9gEpB/Ocl8+W4fnjvkakG1goJ6CBXnkZJKtRXpJaT/I7m+hXRq4HnfIqmeLfn7ZNIt1A2uE1QuKBiAyvEQKsZqpOuSPhMeDl8M/zjC+/n/LIAqfx7R61SovnJDuJrktoeE4hXMCnjxa/DiNyHdFn4MXgWzqbixQPX/DOWQW/KRZSvdk76CF/wQ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MensagemInterrogacao {
            get {
                return ResourceManager.GetString("MensagemInterrogacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAALQAAAC0CAYAAAA9zQYyAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOwgAADsIBFShKgAAAABh0RVh0U29mdHdhcmUAcGFpbnQubmV0IDQuMC45bDN+TgAAHC5JREFUeF7tnQmwHVWZx9kJkISEHdmpCQky4oQl6ChLgJJiSAbCEiSANRQwbIJYFISBkhGUIGjUUscSYTRRCGQEZoQqCxCVbUb2XUBhFIGBAWSVRfb5/bu/O7m8vPfuOX27+5zue35VX/V9753vO993+ry+p8+6TMKd999/f9X33ntvNWQSchAyB7kcubJLbiGdE6R9YojuxYjsHsSfd+GqvFax7BOJYlCZllVFQrZHZiA/Qi7h9y9xfRd5TxWySpQHKK9nkUXIhYh8kU+rkGQFczeR+CBUjuWRtagoOyHfQH6A/AV5R5UrJuSTfOPj9chX+Lwj1wnIchZOYhChAqxIZZiMfB65BHmF3zUSfH+ZywKu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MesnagemInformacao {
            get {
                return ResourceManager.GetString("MesnagemInformacao", resourceCulture);
            }
        }
    }
}
