//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Percolore.Treinamento.Properties
{
	/// <summary>
	///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
	/// </summary>
	// Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
	// através de uma ferramenta como ResGen ou Visual Studio.
	// Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
	// com a opção /str, ou recrie o projeto do VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Treinamento_String_esp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Treinamento_String_esp() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Percolore.Treinamento.Properties.Treinamento_String_esp", typeof(Treinamento_String_esp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para el suministro de los depósitos de colorante, siga con la máxima atención los siguientes pasos:
        ///
        ///⇒ Verificar los colorantes con bajo nivel y separar las embalajes correspondientes en su inventario;
        ///⇒ Coloque el colorante en el mixer y agitar durante al menos 3 minutos.
        ///⇒ Abra la tapa del colorante usando abretapas, hacer una apertura entre 8 y 10 cm y una pequeña abertura en el lado opuesto de la cubierta superior, para hacer un &quot;respiro&quot;. Esto evitará que el colorante sailga sin control de envases  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Abastecimento_001_Texto {
            get {
                return ResourceManager.GetString("Abastecimento_001_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Suministro.
        /// </summary>
        internal static string Abastecimento_001_Titulo {
            get {
                return ResourceManager.GetString("Abastecimento_001_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ⇒ tomar sólo la embalaje del colorante que le será suministrada, verter el contenido cuidadosamente en el tanque.
        ///⇒ Inmediatamente cerrar el depósito;
        ///⇒ Hacer el registro de suministro con el fin de establecer unos niveles seguros de colorante de control y evitar la falta de ella durante las dosificaciones.
        ///⇒ Importante: Evitar verter colorante sobre la vara de las paletas de agitación. Siempre use los bordes laterales para depositar el colorante como la imagen de abajo..
        /// </summary>
        internal static string Abastecimento_002_Texto {
            get {
                return ResourceManager.GetString("Abastecimento_002_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Suministro.
        /// </summary>
        internal static string Abastecimento_002_Titulo {
            get {
                return ResourceManager.GetString("Abastecimento_002_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A continuación, se discuten los principales problemas en el uso de sus equipos, donde podrá aprender a usarlo de manera más productiva y también algunos consejos para el cuidado preventivo que puede garantizar la calidad de sus puntos fuertes y preservación de su dosificadora Percolore!.
        /// </summary>
        internal static string Abertura_Texto {
            get {
                return ResourceManager.GetString("Abertura_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ¡Sea bienvenido!.
        /// </summary>
        internal static string Abertura_Titulo {
            get {
                return ResourceManager.GetString("Abertura_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Su dosificadora es un equipo de precisión y debe ser conservada para operar con la máxima calidad.
        ///Con un poco de cuidado en el mantenimiento preventivo, aun el ahoro que tiene, la calidad se mantiene en sus pigmentaciones.
        ///Limpieza de los bicos dosadores asegura el flujo perfecto de colorante en el momento de la dosificación; por lo tanto tiene la máxima atención a los pasos del proceso requerido para mantener la boquilla en perfecta condiciones de limpieza:
        ///
        ///⇒ Proceso de purga: La dosificadora AD-D8 h [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string CuidadosBasicos_001_Texto {
            get {
                return ResourceManager.GetString("CuidadosBasicos_001_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atención básica.
        /// </summary>
        internal static string CuidadosBasicos_001_Titulo {
            get {
                return ResourceManager.GetString("CuidadosBasicos_001_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Los colorantes son el combustible de su dosificación!
        ///
        ///Mantener depósitos abastecidos y registrar adecuadamente la cantidad en stock, se evitan las interrupciones en la dispensación de una fórmula en el tiempo que se estea haciendo una pintura a su cliente.
        ///Esta precaución también evita la entrada de aire en la bomba, lo que podría provocar un fallo en la cantidad de colorante dispensado, alterando el resultado deseado!
        ///
        ///Importante: No sobre-llenar el depósito hasta el punto de desbordamiento o que obs [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string CuidadosBasicos_002_Texto {
            get {
                return ResourceManager.GetString("CuidadosBasicos_002_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nivel de colorante.
        /// </summary>
        internal static string CuidadosBasicos_002_Titulo {
            get {
                return ResourceManager.GetString("CuidadosBasicos_002_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Poner su maquina dosificadora AD-D8 en un lugar de trabajo definitivo, evitando el desplazamiento constante de la misma.
        ///Si el piso no está correctamente nivelada, ajuste los pies de la máquina para obtener las mejores condiciones de estabilidad y seguridad.
        ///Es importante posicionar la maquina doificadora para que tenga fácil acceso y facilitar las operaciones de suministro de colorante, toma eléctrica con conexión a terra y cualquier mantenimiento técnico..
        /// </summary>
        internal static string CuidadosBasicos_003_Texto {
            get {
                return ResourceManager.GetString("CuidadosBasicos_003_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lugar de trabajo.
        /// </summary>
        internal static string CuidadosBasicos_003_Titulo {
            get {
                return ResourceManager.GetString("CuidadosBasicos_003_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a La operación hacer la pintura por dosificación sigue una secuencia lógica de pasos que les permitan realizar la fórmula/color deseada tan rápidamente y con tranquilidad. A continuación presentamos los pasos:
        ///
        ///⇒ La elección del color (se puede utilizar el nombre del color o su código);
        ///⇒ Seleccione la base para ser pigmentada;
        ///⇒ Seleccione el Embalaje que desea hacer;
        ///⇒ Generación de la fórmula;
        ///⇒ Dosificación de colorantes.
        ///
        ///Importante: Después de la elección de la base y embalaje adecuado solicitad [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Dosagem_001_Texto {
            get {
                return ResourceManager.GetString("Dosagem_001_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dosificación.
        /// </summary>
        internal static string Dosagem_001_Titulo {
            get {
                return ResourceManager.GetString("Dosagem_001_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 
        ///
        ///Felicitaciones!
        ///Usted realizó el entrenamiento completo para el uso de su dosificadora AD-D8
        ///
        ///
        ///En caso necesario, póngase en contacto con nuestro servicio de atención al cliente:
        ///whatsapp: +55 51 96937468
        ///Telefono: +55 51 99740-8288
        ///sac@percolore.com
        ///www.percolore.com.br
        ///
        ///.
        /// </summary>
        internal static string Encerramento_001_Texto {
            get {
                return ResourceManager.GetString("Encerramento_001_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Encerramento_001_Titulo {
            get {
                return ResourceManager.GetString("Encerramento_001_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a La dosificadora hara una solicitación todos los dias para hacer una purga de todos los colorantes.
        ///Este es un procedimiento rápido y necesario para evitar el bloqueo y las bombas y evitar la obstrucción o taponamiento de los bicos por los residuos de colorante seco como resultado de transacciones pasadas.
        ///
        ///Para su seguridad, la máquina no permitirá una nueva operación antes de ejecutar el proceso diario de purga.
        ///Utilice un único recipiente para recoger la pequeña cantidad de colorante a dispensar indiv [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Purga_001_Texto {
            get {
                return ResourceManager.GetString("Purga_001_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Proceso de purga.
        /// </summary>
        internal static string Purga_001_Titulo {
            get {
                return ResourceManager.GetString("Purga_001_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Actualizar volúmenes colorantes siempre que reponer su dosificación.
        ///
        ///Este procedimiento es esencial para evitar que el nivel de colorante sea muy bajo, lo que puede evitar que la exención para correr y causar la formación de bolsas de aire dentro del depósito.
        ///
        ///Puede acceder a la pantalla de volumen del colorante desde la pantalla principal, como en la imagen de abajo.
        ///En la pantalla que se abre, tenga en cuenta lo siguiente:
        ///
        ///⇒ En la columna de la izquierda aparece el nombre del colorante;
        ///⇒ En la [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string RegistroAbastecimento_001_Texto {
            get {
                return ResourceManager.GetString("RegistroAbastecimento_001_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro de suministro.
        /// </summary>
        internal static string RegistroAbastecimento_001_Titulo {
            get {
                return ResourceManager.GetString("RegistroAbastecimento_001_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formación Dosadora AD-D8.
        /// </summary>
        internal static string UI_Titulo {
            get {
                return ResourceManager.GetString("UI_Titulo", resourceCulture);
            }
        }
    }
}