//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Percolore.Treinamento.Properties
{
	/// <summary>
	///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
	/// </summary>
	// Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
	// através de uma ferramenta como ResGen ou Visual Studio.
	// Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
	// com a opção /str, ou recrie o projeto do VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Treinamento_String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Treinamento_String() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Percolore.Treinamento.Properties.Treinamento_String", typeof(Treinamento_String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para abastecer os reservatórios de colorante de sua dosadora, siga com máxima atenção as seguintes etapas:
        ///
        ///⇒ Verifique os corantes com nível baixo e separe as embalagens correspondentes no seu estoque;
        ///⇒ Coloque a embalagem no seu agitador Percolore e agite por no mínimo, 3 minutos.
        ///⇒ Abra a tampa da embalagem utilizando abridor de latas, faça um rasgo entre 8 e 10 cm e uma pequena abertura no lado oposto da tampa superior, para fazer um “respiro”. Isso evitará que o colorante saia da embalagem de modo [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Abastecimento_001_Texto {
            get {
                return ResourceManager.GetString("Abastecimento_001_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abastecimento.
        /// </summary>
        internal static string Abastecimento_001_Titulo {
            get {
                return ResourceManager.GetString("Abastecimento_001_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ⇒ Tire somente a tampa do corante que será abastecido, despeje o conteúdo, com cuidado, no reservatório.
        ///⇒ Feche imediatamente o reservatório;
        ///⇒ Efetue o registro de abastecimento a fim de estabelecer um controle seguro dos níveis de corantes e evitar a falta dos mesmos durante as dosagens.
        ///⇒ Importante: Evite despejar corante sobre a haste das pás de agitação. Utilize sempre as bordas laterais para depositar o corante, conforme imagem abaixo..
        /// </summary>
        internal static string Abastecimento_002_Texto {
            get {
                return ResourceManager.GetString("Abastecimento_002_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abastecimento.
        /// </summary>
        internal static string Abastecimento_002_Titulo {
            get {
                return ResourceManager.GetString("Abastecimento_002_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A seguir, abordaremos os principais assuntos relativos à utilização de seu equipamento, onde você aprenderá a utilizá-lo com maior produtividade e também algumas dicas de cuidados preventivos que podem garantir a qualidade de suas dosagens e preservação de sua máquina!.
        /// </summary>
        internal static string Abertura_Texto {
            get {
                return ResourceManager.GetString("Abertura_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seja bem-vindo!.
        /// </summary>
        internal static string Abertura_Titulo {
            get {
                return ResourceManager.GetString("Abertura_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua Dosadora é um equipamento de precisão e precisa ser preservada para que opere com máxima qualidade.
        ///Com alguns cuidados em manutenção preventiva, além de economia, você terá qualidade continua em suas pigmentações. 
        ///A limpeza dos bicos garante o fluxo perfeito dos colorantes no momento da dosagem; portanto, tenha máxima atenção às etapas do processo necessário para manter os bicos em perfeitas condições:
        ///
        ///⇒ Processo de purga: sua AD-D8 solicitará diariamente, antes do início de um novo ciclo de trab [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string CuidadosBasicos_001_Texto {
            get {
                return ResourceManager.GetString("CuidadosBasicos_001_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cuidados básicos.
        /// </summary>
        internal static string CuidadosBasicos_001_Titulo {
            get {
                return ResourceManager.GetString("CuidadosBasicos_001_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Os colorantes são o combustível de sua dosadora!
        ///
        ///Mantendo os reservatórios abastecidos e registrando corretamente a quantidade em estoque, você evitará interrupções na dispensa de uma fórmula na hora de atender seu cliente.
        ///Esse cuidado também evita a entrada de ar nas bombas, o que poderia provocar uma falha na quantidade de colorante dispensada, alterando o resultado desejado!
        ///
        ///Importante: Não abasteça excessivamente o reservatório a ponto de transbordá-lo ou prejudicar o processo automático de agit [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string CuidadosBasicos_002_Texto {
            get {
                return ResourceManager.GetString("CuidadosBasicos_002_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nível de colorante.
        /// </summary>
        internal static string CuidadosBasicos_002_Titulo {
            get {
                return ResourceManager.GetString("CuidadosBasicos_002_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Procure deixar sua dosadora em um local definitivo de trabalho, evitando o deslocamento constante do equipamento.
        ///Caso o piso não esteja corretamente nivelado, ajuste os pés de sua máquina até obter a melhor condição de estabilidade e segurança.
        ///É importante posicionar sua dosadora em local de fácil acesso para facilitar as operações de abastecimento, energia elétrica e eventuais manutenções técnicas..
        /// </summary>
        internal static string CuidadosBasicos_003_Texto {
            get {
                return ResourceManager.GetString("CuidadosBasicos_003_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Local de trabalho.
        /// </summary>
        internal static string CuidadosBasicos_003_Titulo {
            get {
                return ResourceManager.GetString("CuidadosBasicos_003_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A operação de dosagens segue uma sequência lógica de etapas que lhes permitirão executar a fórmula desejada como rapidez e tranquilidade. Abaixo as etapas que serão apresentadas:
        ///
        ///⇒ Escolha da cor (podendo utilizar o nome da cor ou o seu código);
        ///⇒ Escolha da base que será pigmentada;
        ///⇒ Escolha da embalagem que será fornecida;
        ///⇒ Geração da fórmula;
        ///⇒ Dispensa de colorantes.
        ///
        ///Importante: Após a escolha da base adequada e embalagem solicitada pelo cliente, abra a mesma e coloque-a sobre a bandeja na p [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Dosagem_001_Texto {
            get {
                return ResourceManager.GetString("Dosagem_001_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dosagem.
        /// </summary>
        internal static string Dosagem_001_Titulo {
            get {
                return ResourceManager.GetString("Dosagem_001_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 
        ///
        ///Parabéns!
        ///Você realizou o treinamento completo para uso de sua Dosadora AD-D8.
        ///
        ///
        ///Sempre que necessário, contate nosso SAC:
        ///whatsapp: +55 51 96937468
        ///+55 51 3107 6600
        ///sac@percolore.com
        ///www.percolore.com.br
        ///
        ///.
        /// </summary>
        internal static string Encerramento_001_Texto {
            get {
                return ResourceManager.GetString("Encerramento_001_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Encerramento_001_Titulo {
            get {
                return ResourceManager.GetString("Encerramento_001_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua Dosadora solicitará diariamente purga de todos os colorantes.
        ///Este é um procedimento rápido e necessário para e evitar o travamento das bombas e prevenir a obstrução ou entupimento dos bicos por resíduos de corante seco resultante de operações anteriores.
        ///
        ///Para sua segurança, o equipamento não permitirá uma nova dosagem antes de executar o processo.
        ///Utilize um recipiente único para coletar a pequena quantidade de colorante que será dispensada individualmente por todos os bicos (cores).
        ///
        ///Para isso, [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Purga_001_Texto {
            get {
                return ResourceManager.GetString("Purga_001_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processo de Purga.
        /// </summary>
        internal static string Purga_001_Titulo {
            get {
                return ResourceManager.GetString("Purga_001_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atualize os volumes de colorantes sempre que reabastecer sua dosadora.
        ///
        ///Este procedimento é fundamental para evitar que o nível de colorante fique muito baixo, o que pode impedir que a dispensa seja executada e ocasionar a formação de bolsas de ar dentro do reservatório.
        ///
        ///Você pode acessar a tela de volume de colorantes a partir da sua tela principal, como na imagem abaixo.
        ///Na tela que se abre, observe o seguinte:
        ///
        ///⇒ Na coluna esquerda é exibido o nome do colorante;
        ///⇒ Na coluna intermediária é exibi [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string RegistroAbastecimento_001_Texto {
            get {
                return ResourceManager.GetString("RegistroAbastecimento_001_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro de abastecimento.
        /// </summary>
        internal static string RegistroAbastecimento_001_Titulo {
            get {
                return ResourceManager.GetString("RegistroAbastecimento_001_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Treinamento Dosadora AD-D8.
        /// </summary>
        internal static string UI_Titulo {
            get {
                return ResourceManager.GetString("UI_Titulo", resourceCulture);
            }
        }
    }
}