//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Percolore.Treinamento.Properties
{
	/// <summary>
	///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
	/// </summary>
	// Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
	// através de uma ferramenta como ResGen ou Visual Studio.
	// Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
	// com a opção /str, ou recrie o projeto do VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Treinamento_String_eng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Treinamento_String_eng() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Percolore.Treinamento.Properties.Treinamento_String_eng", typeof(Treinamento_String_eng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a To fill the colorant canisters of your Dispenser Machine, follow these steps carefully:
        ///
        ///⇒ Check the low level dyes and separate the corresponding packages in your stock;
        ///⇒ Place the package on your Percolore shaker and shake for at least 3 minutes;
        ///⇒ Open the package lid using a can opener, make a tear between 8 and 10 cm and a small opening on the opposite side of the top cover to make a &quot;breath&quot;. This will prevent the colorant from coming out of the package in an out-of-control way at the time of dum [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Abastecimento_001_Texto {
            get {
                return ResourceManager.GetString("Abastecimento_001_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Supply.
        /// </summary>
        internal static string Abastecimento_001_Titulo {
            get {
                return ResourceManager.GetString("Abastecimento_001_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ⇒ Remove only the lid of the dye to be filled, pour the contents carefully into the reservoir.
        ///⇒ Close the container immediately;
        ///⇒ Make the supply register in order to establish a safe control of the dye levels and avoid the lack of them during the dosages.
        ///⇒ Important: Avoid spilling dye on the mixing pads shaft. Always use the side edges to deposit the dye, as shown below..
        /// </summary>
        internal static string Abastecimento_002_Texto {
            get {
                return ResourceManager.GetString("Abastecimento_002_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Supply.
        /// </summary>
        internal static string Abastecimento_002_Titulo {
            get {
                return ResourceManager.GetString("Abastecimento_002_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Next, we will address the main issues related to the use of your equipment, where you will learn how to use it with greater productivity and also some preventive care tips that can ensure the quality of your dosages and preservation of your machine!.
        /// </summary>
        internal static string Abertura_Texto {
            get {
                return ResourceManager.GetString("Abertura_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Welcome!.
        /// </summary>
        internal static string Abertura_Titulo {
            get {
                return ResourceManager.GetString("Abertura_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Your Dispenser Machine is a precision equipment and needs to be preserved to operate with maximum quality.
        ///With some care in preventive maintenance, in addition to economy, you will have continuous quality in your pigmentations. 
        ///Nozzle cleaning ensures perfect colorant flow at dosing time, so pay maximum attention to the process steps required to keep the nozzles in perfect condition:
        ///
        ///⇒ Purge process: Your AD-D8 will request daily, before the start of a new work cycle, the execution of the purge proce [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string CuidadosBasicos_001_Texto {
            get {
                return ResourceManager.GetString("CuidadosBasicos_001_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Basic care.
        /// </summary>
        internal static string CuidadosBasicos_001_Titulo {
            get {
                return ResourceManager.GetString("CuidadosBasicos_001_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Colorants are the fuel of your Dispenser Machine!
        ///
        ///By keeping the reservoirs filled and correctly recording the quantity in stock, you will avoid interruptions in the dispensation of a formula at the time of serving your customer.
        ///This precaution also prevents air from entering the pumps, which could lead to a failure in the amount of colorant dispensed, changing the desired result!
        ///
        ///Important: Do not overfill the tank to such an extent that it overflows or impairs the automatic stirring process, so pl [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string CuidadosBasicos_002_Texto {
            get {
                return ResourceManager.GetString("CuidadosBasicos_002_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Colorant Level.
        /// </summary>
        internal static string CuidadosBasicos_002_Titulo {
            get {
                return ResourceManager.GetString("CuidadosBasicos_002_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Try to leave your Dispenser Machine in a definitive place of work, avoiding the constant displacement of the equipment.
        ///If the floor is not correctly levelled, adjust the feet of your machine until you get the best stability and safety condition.
        ///It is important to position your metering unit in a location with easy access to facilitate the operations of supply, electric power and eventual technical maintenance..
        /// </summary>
        internal static string CuidadosBasicos_003_Texto {
            get {
                return ResourceManager.GetString("CuidadosBasicos_003_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Work Place.
        /// </summary>
        internal static string CuidadosBasicos_003_Titulo {
            get {
                return ResourceManager.GetString("CuidadosBasicos_003_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The dosage operation follows a logical sequence of steps that will allow them to execute the desired formula quickly and smoothly. Below are the steps that will be presented:
        ///
        ///⇒ Choice of color (you can use the name of the color or its code);
        ///⇒ Choice of the base that will be pigmented;
        ///⇒ Choice of packaging that will be provided;
        ///⇒ Formula generation;
        ///⇒ Colorant dispensing.
        ///
        ///Important: After choosing the appropriate base and packaging requested by the customer, open it and place it on the tray in t [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Dosagem_001_Texto {
            get {
                return ResourceManager.GetString("Dosagem_001_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dosage.
        /// </summary>
        internal static string Dosagem_001_Titulo {
            get {
                return ResourceManager.GetString("Dosagem_001_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 
        ///
        ///Congratulations!
        ///You have completed the complete training for the use of your AD-D8.
        ///
        ///
        ///Whenever necessary, contact our Customer Service:
        ///whatsapp: +55 51 996937468
        ///+55 51 3107 6600
        ///sac@percolore.com
        ///www.percolore.com.br
        ///
        ///.
        /// </summary>
        internal static string Encerramento_001_Texto {
            get {
                return ResourceManager.GetString("Encerramento_001_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Encerramento_001_Titulo {
            get {
                return ResourceManager.GetString("Encerramento_001_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Your Dispenser Machine will request daily purging of all colorants.
        ///This is a quick and necessary procedure to prevent the pumps from clogging the nozzles with dry dye residue from previous operations.
        ///
        ///For your safety, the equipment will not allow a new dosage before performing this process.
        ///Use a single container to collect the small amount of colorant that will be dispensed individually by all nozzles (colors).
        ///
        ///To do this, simply move the nozzle release mechanism back and click the purge button on [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Purga_001_Texto {
            get {
                return ResourceManager.GetString("Purga_001_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Purging Process.
        /// </summary>
        internal static string Purga_001_Titulo {
            get {
                return ResourceManager.GetString("Purga_001_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Update colorant volumes every time you refill your Dispenser Machine.
        ///
        ///This procedure is critical to prevent the colorant level from becoming too low, which can prevent dispensing from being performed and cause air pockets to form inside the reservoir.
        ///
        ///You can access the colorant volume screen from your main screen, as in the image below.
        ///On the following screen observe:
        ///
        ///⇒ The name of the colorant is displayed in the left column;
        ///⇒ The colorant circuit (reservoir and pump) is displayed in the inte [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string RegistroAbastecimento_001_Texto {
            get {
                return ResourceManager.GetString("RegistroAbastecimento_001_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Supply record.
        /// </summary>
        internal static string RegistroAbastecimento_001_Titulo {
            get {
                return ResourceManager.GetString("RegistroAbastecimento_001_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AD-D8 Training.
        /// </summary>
        internal static string UI_Titulo {
            get {
                return ResourceManager.GetString("UI_Titulo", resourceCulture);
            }
        }
    }
}